// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSPZ2Y-TXYmdi0kfWkuYkkc2bqOrq4UbI',
    appId: '1:321795651689:web:0361f32d85d810cfd70af8',
    messagingSenderId: '321795651689',
    projectId: 'flutterauth-ce568',
    authDomain: 'flutterauth-ce568.firebaseapp.com',
    storageBucket: 'flutterauth-ce568.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQebgyTDpCDfypZmwvOn1UcCo9j2irW8w',
    appId: '1:321795651689:android:b2524dd001617bb2d70af8',
    messagingSenderId: '321795651689',
    projectId: 'flutterauth-ce568',
    storageBucket: 'flutterauth-ce568.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoUO4vLtWDFQ3-JBdUvOQWZcTzrksU_kg',
    appId: '1:321795651689:ios:348d01522a73603fd70af8',
    messagingSenderId: '321795651689',
    projectId: 'flutterauth-ce568',
    storageBucket: 'flutterauth-ce568.appspot.com',
    iosClientId: '321795651689-mtjml3acgeb14ius5kshovn8fvq8nikb.apps.googleusercontent.com',
    iosBundleId: 'com.example.coffeeFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoUO4vLtWDFQ3-JBdUvOQWZcTzrksU_kg',
    appId: '1:321795651689:ios:348d01522a73603fd70af8',
    messagingSenderId: '321795651689',
    projectId: 'flutterauth-ce568',
    storageBucket: 'flutterauth-ce568.appspot.com',
    iosClientId: '321795651689-mtjml3acgeb14ius5kshovn8fvq8nikb.apps.googleusercontent.com',
    iosBundleId: 'com.example.coffeeFlutter',
  );
}
